version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=main,test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./docker/pg:/docker-entrypoint-initdb.d
    networks:
      - apbp-network

  clickhouse:
    image: 'clickhouse/clickhouse-server'
    ports:
      - 8123:8123
      - 9000:9000
    networks:
      - apbp-network

volumes:
  database-data:

networks:
  apbp-network:
